apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-exposer
automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: ingress-exposer-secret
  annotations:
    kubernetes.io/service-account.name: ingress-exposer
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-location-right
rules:
- apiGroups: ["*"]
  resources: ["namespaces","ingresses"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-ingress-global
subjects:
- kind: ServiceAccount
  name: ingress-exposer
  namespace: default
roleRef:
  kind: ClusterRole
  name: ingress-location-right
  apiGroup: rbac.authorization.k8s.io